In [1]:
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd

In [4]:
pd.set_option("display.max.rows", 30)
pd.set_option("display.max.columns", 30)
pd.set_option("display.max.colwidth", -1)

In [5]:
df = pd.read_csv('train.csv')
df.head()

id  \
0  0    
1  1    
2  2    
3  3    
4  4    

                                                                                           title  \
0  House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It               
1  FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart                                         
2  Why the Truth Might Get You Fired                                                               
3  15 Civilians Killed In Single US Airstrike Have Been Identified                                 
4  Iranian woman jailed for fictional unpublished story about woman stoned to death for adultery   

               author  \
0  Darrell Lucus        
1  Daniel J. Flynn      
2  Consortiumnews.com   
3  Jessica Purkiss      
4  Howard Portnoy       

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

In [6]:
df.shape

(20800, 5)

In [7]:
df.isnull().sum()

id        0   
title     558 
author    1957
text      39  
label     0   
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [9]:
df.sample(10)

id  \
19345  19345   
9334   9334    
13009  13009   
2841   2841    
3887   3887    
2281   2281    
20184  20184   
12850  12850   
2717   2717    
14737  14737   

                                                                                             title  \
19345  For Kansas Coach Bill Self, Sticking to Basketball Is Convenient - The New York Times         
9334   Twitter Users Mock Hillary Clinton For Wishing Herself a Happy Birthday                       
13009  Wilbur Ross: Free Trade Deal Needed with Europe to Reduce Unfair Tariffs                      
2841   Close to Half of American Adults Infected With HPV, Survey Finds - The New York Times         
3887   Duterte Says ’Spare No One’ as Islamic State Beheads Police Chief, Stages Mass Prison Break   
2281   Yale Sets Policy That Could Allow Renaming of Calhoun College - The New York Times            
20184  Kaine says Clinton would seek updated war-making powers                                       
12850  Ecuador Votes as Latin America’s Left Sags, a Generation of Icons Gone - The New York Times   
2717   The Doubt Machine: Inside The Koch Brothers’ War on Climate Science                           
14737  VIDEO : Trump Surges to Tie Clinton in BLUE STATE Colorado – TruthFeed                        

                               author  \
19345  Juliet Macur                     
9334   Kim Smith                        
13009  John Hayward                     
2841   Nicholas Bakalar                 
3887   Frances Martel                   
2281   Jennifer Schuessler              
20184  Larry                            
12850  Nicholas Casey and Maggy Ayala   
2717   Rowan Wolf                       
14737  NaN                              

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [10]:
## drop nan values

df = df.dropna()

In [11]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [12]:
#get the independent features

X = df.drop(['label'], axis = 1)

In [13]:
## get the dependent features

y = df['label']

In [14]:
X['author'].value_counts()

Pam Key                                                        243
admin                                                          193
Jerome Hudson                                                  166
Charlie Spiering                                               141
John Hayward                                                   140
                                                              ... 
Cache Valley Prepper                                           1  
Jamie Diamond                                                  1  
Nikolaï Litovkine                                              1  
Are black holes fountains of creation? – The Conscious Mind    1  
Amy Chozick and Michael D. Shear                               1  
Name: author, Length: 3838, dtype: int64

In [15]:
import tensorflow as tf

In [16]:
tf.__version__

'2.5.0'

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [18]:
# Vocabulary size

vocab_size = 5000

# Onehot Representation


In [19]:
messages = X.copy()

In [20]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [21]:
messages.reset_index(inplace = True)

In [22]:
import nltk
import re
from nltk.corpus import stopwords

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saira\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
# dataset preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0, len(messages)):
    
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [25]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [26]:
onehot_repr = [one_hot(words, vocab_size) for words in corpus]
onehot_repr

[[2135, 971, 2040, 1851, 2500, 2467, 431, 1600, 4718, 1547],
 [4748, 1177, 2633, 2806, 2868, 4512, 2138],
 [4930, 4847, 1196, 1611],
 [3274, 3102, 1438, 703, 3816, 2094],
 [1637, 2868, 220, 2416, 1496, 935, 2868, 3264, 838, 3561],
 [4833,
  4757,
  3082,
  34,
  867,
  3717,
  837,
  3954,
  1666,
  2366,
  1067,
  1699,
  2688,
  4209,
  2138],
 [2992, 1118, 855, 3841, 164, 1171, 1636, 2506, 382, 1836, 936],
 [374, 3685, 1391, 3449, 1437, 4747, 3717, 529, 382, 1836, 936],
 [3350, 2000, 2299, 353, 1569, 2310, 4673, 2973, 3717, 2787],
 [2068, 4560, 1365, 3578, 3440, 1528, 915, 696],
 [3552, 3170, 4453, 3353, 1037, 2407, 648, 3044, 884, 2480, 2459],
 [703, 3629, 2500, 2310, 3717, 1437],
 [4919, 680, 3963, 2550, 1243, 488, 4551, 3455, 608],
 [4577, 4087, 3897, 36, 2379, 1220, 918, 382, 1836, 936],
 [2860, 2197, 2918, 636, 4434, 382, 1836, 936],
 [2732, 387, 2821, 3656, 4272, 586, 942, 1894, 3686, 3142],
 [4914, 4925, 1177],
 [1800, 731, 4160, 485, 3717, 2637, 811, 2138],
 [2400, 452, 2633

In [27]:
len(onehot_repr)

18285

# Embedding Representation

In [28]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 1600 4718 1547]
 [   0    0    0 ... 2868 4512 2138]
 [   0    0    0 ... 4847 1196 1611]
 ...
 [   0    0    0 ...  382 1836  936]
 [   0    0    0 ... 3690 3495 2131]
 [   0    0    0 ...  417 1094 1467]]


In [29]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2135,
        971, 2040, 1851, 2500, 2467,  431, 1600, 4718, 1547])

In [30]:
# Creating model

embedding_vector_features = 40
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [31]:
len(embedded_docs), y.shape

(18285, (18285,))

In [32]:
import numpy as np 
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [33]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.33, random_state=42)

In [35]:
print("The shape of X_train: {} ".format(X_train.shape))
print("The shape of X_test: {}".format(X_test.shape))
print("The shape of y_train: {}".format(y_train.shape))
print("The shape of y_test: {}".format(y_test.shape))

The shape of X_train: (12250, 20) 
The shape of X_test: (6035, 20)
The shape of y_train: (12250,)
The shape of y_test: (6035,)


# Model Training

In [36]:
# finally Training

model.fit(X_train, y_train, validation_data= (X_test, y_test), epochs = 10, batch_size = 64, verbose = 1)

Epoch 1/10
192/192 [==============================] - 10s 35ms/step - loss: 0.3409 - accuracy: 0.8357 - val_loss: 0.1918 - val_accuracy: 0.9190
Epoch 2/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1414 - accuracy: 0.9442 - val_loss: 0.1919 - val_accuracy: 0.9183
Epoch 3/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0980 - accuracy: 0.9642 - val_loss: 0.2211 - val_accuracy: 0.9186
Epoch 4/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0705 - accuracy: 0.9753 - val_loss: 0.2341 - val_accuracy: 0.9185
Epoch 5/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0516 - accuracy: 0.9821 - val_loss: 0.2434 - val_accuracy: 0.9137
Epoch 6/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0350 - accuracy: 0.9885 - val_loss: 0.3859 - val_accuracy: 0.9099
Epoch 7/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0247 - accuracy: 0.9930 - val_loss: 0.3764 - val_accuracy: 0.917

# Adding Dropout

In [40]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [41]:
model.fit(X_train, y_train, validation_data= (X_test, y_test), epochs = 10, batch_size = 64, verbose = 1)

Epoch 1/10
192/192 [==============================] - 11s 39ms/step - loss: 0.3430 - accuracy: 0.8389 - val_loss: 0.1939 - val_accuracy: 0.9167
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1514 - accuracy: 0.9397 - val_loss: 0.1878 - val_accuracy: 0.9211
Epoch 3/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1125 - accuracy: 0.9555 - val_loss: 0.2044 - val_accuracy: 0.9160
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0831 - accuracy: 0.9682 - val_loss: 0.2466 - val_accuracy: 0.9221
Epoch 5/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0617 - accuracy: 0.9779 - val_loss: 0.2517 - val_accuracy: 0.9215
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0437 - accuracy: 0.9856 - val_loss: 0.2808 - val_accuracy: 0.9074
Epoch 7/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0366 - accuracy: 0.9882 - val_loss: 0.3190 - val_accuracy: 0.913

# Performance Metrics and Accuracy


In [42]:
y_pred = model.predict_classes(X_test)

In [43]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[3175,  244],
       [ 289, 2327]], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9116818558409279