In [1]:
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option("display.max.rows", 30)
pd.set_option("display.max.columns", 30)
pd.set_option("display.max.colwidth", -1)

In [5]:
df = pd.read_csv('train.csv')
df.head()

id  \
0  0    
1  1    
2  2    
3  3    
4  4    

                                                                                           title  \
0  House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It               
1  FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart                                         
2  Why the Truth Might Get You Fired                                                               
3  15 Civilians Killed In Single US Airstrike Have Been Identified                                 
4  Iranian woman jailed for fictional unpublished story about woman stoned to death for adultery   

               author  \
0  Darrell Lucus        
1  Daniel J. Flynn      
2  Consortiumnews.com   
3  Jessica Purkiss      
4  Howard Portnoy       

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

In [6]:
# Drop na values

df = df.dropna()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18285 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      18285 non-null  int64 
 1   title   18285 non-null  object
 2   author  18285 non-null  object
 3   text    18285 non-null  object
 4   label   18285 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 857.1+ KB


In [8]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [9]:
df['label'].value_counts()

0    10361
1    7924 
Name: label, dtype: int64

In [10]:
# Get the Independent Features

X = df.drop(['label'], axis = 1)

In [11]:
y = df['label']

In [12]:
X.shape

(18285, 4)

In [13]:
y.shape

(18285,)

In [14]:
import tensorflow as tf

In [15]:
tf.__version__

'2.5.0'

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Dense, Bidirectional, Dropout

In [17]:
# Vocabulary size

vocab_size = 5000

# Onehot Representation


In [18]:
messages = X.copy()

In [19]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [20]:
messages.reset_index(inplace = True)

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saira\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
# Dataset preprocessing 

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0, len(messages)):
    
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i]) #except alphabets remaining all characters are replace with space.
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [24]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [25]:
onehot_repr = [one_hot(words, vocab_size) for words in corpus]
onehot_repr

[[3638, 3622, 3679, 2823, 2742, 4281, 515, 3928, 19, 360],
 [3453, 3997, 1124, 3554, 4037, 2433, 1982],
 [2305, 4702, 139, 3151],
 [2032, 749, 2840, 1891, 2073, 2535],
 [703, 4037, 3070, 2333, 2336, 1716, 4037, 2261, 1433, 557],
 [4101,
  4321,
  2378,
  3804,
  1378,
  124,
  2693,
  3604,
  4349,
  2856,
  2144,
  3695,
  4890,
  3326,
  1982],
 [4779, 1861, 4287, 3106, 1218, 3017, 3817, 253, 1507, 4537, 58],
 [3909, 1697, 1434, 4710, 3515, 754, 124, 3793, 1507, 4537, 58],
 [743, 571, 3845, 1693, 1053, 1266, 2793, 2944, 124, 2052],
 [4890, 4152, 3991, 3053, 143, 3586, 1153, 463],
 [3336, 1151, 4818, 2969, 1344, 835, 3079, 4409, 3052, 2856, 4779],
 [1891, 3558, 2742, 1266, 124, 3515],
 [4242, 306, 1095, 1712, 2251, 3025, 1802, 1165, 4863],
 [4707, 987, 3328, 8, 2908, 2924, 1779, 1507, 4537, 58],
 [1281, 2588, 4610, 2114, 3675, 1507, 4537, 58],
 [229, 670, 2858, 763, 4061, 3492, 1775, 2985, 1886, 2642],
 [3313, 4599, 3997],
 [4312, 1657, 2470, 1238, 124, 3599, 1520, 1982],
 [3994, 4165

# Embedding Representation

In [26]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 3928   19  360]
 [   0    0    0 ... 4037 2433 1982]
 [   0    0    0 ... 4702  139 3151]
 ...
 [   0    0    0 ... 1507 4537   58]
 [   0    0    0 ... 1842 2441 4123]
 [   0    0    0 ... 4805 1133  685]]


In [27]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3638,
       3622, 3679, 2823, 2742, 4281,  515, 3928,   19,  360])

In [28]:
# Creating model 

embedding_vector_features = 40

model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
# Creating model 

embedding_vector_features = 40

model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length = sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
len(embedded_docs), y.shape

(18285, (18285,))

In [30]:
import numpy as np 
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [31]:
X_final

array([[   0,    0,    0, ..., 3928,   19,  360],
       [   0,    0,    0, ..., 4037, 2433, 1982],
       [   0,    0,    0, ..., 4702,  139, 3151],
       ...,
       [   0,    0,    0, ..., 1507, 4537,   58],
       [   0,    0,    0, ..., 1842, 2441, 4123],
       [   0,    0,    0, ..., 4805, 1133,  685]])

In [32]:
y_final

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [33]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [46]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 11s 39ms/step - loss: 0.3407 - accuracy: 0.8375 - val_loss: 0.2456 - val_accuracy: 0.9090
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1489 - accuracy: 0.9398 - val_loss: 0.1880 - val_accuracy: 0.9215- loss: 0.1477 - ac
Epoch 3/10
192/192 [==============================] - 7s 34ms/step - loss: 0.1100 - accuracy: 0.9613 - val_loss: 0.2100 - val_accuracy: 0.9215
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0860 - accuracy: 0.9698 - val_loss: 0.2310 - val_accuracy: 0.9163
Epoch 5/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0643 - accuracy: 0.9780 - val_loss: 0.2610 - val_accuracy: 0.9155
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0491 - accuracy: 0.9833 - val_loss: 0.2737 - val_accuracy: 0.9145
Epoch 7/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0357 - accuracy: 0.9882 - val_loss: 0.3187 - 

# Adding Dropout

In [45]:
from tensorflow.keras.layers import Dropout

# Creating model

embedding_vector_features = 40
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length = sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])


# Performance Metrics and Accuracy

In [47]:
y_pred = model.predict_classes(X_test)

In [48]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[3072,  347],
       [ 185, 2431]], dtype=int64)

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.911847555923778